App\Request\ProductUpdateRequest:
  properties:
    title:
      - NotBlank: ~
      - Type:
          type: 'string'
      - Length:
          min: 2
          max: 255
    price:
      - NotBlank: ~
      - Type:
          type: 'integer'
      - PositiveOrZero: ~
